-- Seed medicines_catalog and lab_tests_catalog from the same ~190-entry
-- dataset used by backend_python/scripts/seed_medicine_catalog.py and
-- frontend/src/database/seed.ts. Idempotent — skips if already populated.

do $$
begin
  if (select count(*) from medicines_catalog) = 0 then
    insert into medicines_catalog (name, type, strength, manufacturer) values
  ('Amoxicillin 500mg', 'Capsule', '500mg', 'Cipla'),
  ('Amoxicillin 250mg', 'Capsule', '250mg', 'Cipla'),
  ('Augmentin 625mg', 'Tablet', '625mg', 'GSK'),
  ('Augmentin 375mg', 'Tablet', '375mg', 'GSK'),
  ('Azithromycin 500mg', 'Tablet', '500mg', 'Alkem'),
  ('Azithromycin 250mg', 'Tablet', '250mg', 'Alkem'),
  ('Ciprofloxacin 500mg', 'Tablet', '500mg', 'Cipla'),
  ('Cefixime 200mg', 'Tablet', '200mg', 'Mankind'),
  ('Cefpodoxime 200mg', 'Tablet', '200mg', 'Lupin'),
  ('Doxycycline 100mg', 'Capsule', '100mg', 'Sun Pharma'),
  ('Metronidazole 400mg', 'Tablet', '400mg', 'Abbott'),
  ('Levofloxacin 500mg', 'Tablet', '500mg', 'Cipla'),
  ('Ofloxacin 200mg', 'Tablet', '200mg', 'Cipla'),
  ('Clindamycin 300mg', 'Capsule', '300mg', 'Intas'),
  ('Norfloxacin 400mg', 'Tablet', '400mg', 'Cipla'),
  ('Paracetamol 500mg', 'Tablet', '500mg', 'GSK'),
  ('Paracetamol 650mg', 'Tablet', '650mg', 'Micro Labs'),
  ('Ibuprofen 400mg', 'Tablet', '400mg', 'Cipla'),
  ('Diclofenac 50mg', 'Tablet', '50mg', 'Novartis'),
  ('Aceclofenac 100mg', 'Tablet', '100mg', 'IPCA'),
  ('Naproxen 500mg', 'Tablet', '500mg', 'Sun Pharma'),
  ('Nimesulide 100mg', 'Tablet', '100mg', 'Panacea'),
  ('Combiflam', 'Tablet', '400+325mg', 'Sanofi'),
  ('Flexon MR', 'Tablet', '500mg', 'Aristo'),
  ('Zerodol SP', 'Tablet', '100+15+325mg', 'IPCA'),
  ('Tramadol 50mg', 'Capsule', '50mg', 'Intas'),
  ('Pantoprazole 40mg', 'Tablet', '40mg', 'Alkem'),
  ('Omeprazole 20mg', 'Capsule', '20mg', 'Dr. Reddys'),
  ('Rabeprazole 20mg', 'Tablet', '20mg', 'Cadila'),
  ('Domperidone 10mg', 'Tablet', '10mg', 'Torrent'),
  ('Ondansetron 4mg', 'Tablet', '4mg', 'Sun Pharma'),
  ('Sucralfate 1g', 'Syrup', '1g/5ml', 'Abbott'),
  ('Ranitidine 150mg', 'Tablet', '150mg', 'Cipla'),
  ('Dicyclomine 20mg', 'Tablet', '20mg', 'Abbott'),
  ('Mebeverine 135mg', 'Tablet', '135mg', 'Abbott'),
  ('ORS Powder', 'Powder', '21.8g', 'WHO Formula'),
  ('Cetirizine 10mg', 'Tablet', '10mg', 'Dr. Reddys'),
  ('Levocetirizine 5mg', 'Tablet', '5mg', 'Glenmark'),
  ('Fexofenadine 120mg', 'Tablet', '120mg', 'Sanofi'),
  ('Fexofenadine 180mg', 'Tablet', '180mg', 'Sanofi'),
  ('Montelukast 10mg', 'Tablet', '10mg', 'Sun Pharma'),
  ('Chlorpheniramine 4mg', 'Tablet', '4mg', 'GSK'),
  ('Hydroxyzine 25mg', 'Tablet', '25mg', 'UCB'),
  ('Salbutamol 4mg', 'Tablet', '4mg', 'Cipla'),
  ('Salbutamol Inhaler', 'Inhaler', '100mcg', 'Cipla'),
  ('Budesonide Inhaler', 'Inhaler', '200mcg', 'Cipla'),
  ('Dextromethorphan Syrup', 'Syrup', '10mg/5ml', 'Abbott'),
  ('Ambroxol 30mg', 'Tablet', '30mg', 'Intas'),
  ('Guaifenesin Syrup', 'Syrup', '100mg/5ml', 'Alkem'),
  ('Deriphyllin Retard 150mg', 'Tablet', '150mg', 'Franco Indian'),
  ('Levosalbutamol Nebuliser', 'Drops', '1.25mg/ml', 'Cipla'),
  ('Codeine Phosphate 10mg', 'Tablet', '10mg', 'Piramal'),
  ('Amlodipine 5mg', 'Tablet', '5mg', 'Pfizer'),
  ('Amlodipine 10mg', 'Tablet', '10mg', 'Pfizer'),
  ('Telmisartan 40mg', 'Tablet', '40mg', 'Glenmark'),
  ('Losartan 50mg', 'Tablet', '50mg', 'Torrent'),
  ('Atenolol 50mg', 'Tablet', '50mg', 'IPCA'),
  ('Metoprolol 50mg', 'Tablet', '50mg', 'AstraZeneca'),
  ('Enalapril 5mg', 'Tablet', '5mg', 'Cadila'),
  ('Aspirin 75mg', 'Tablet', '75mg', 'USV'),
  ('Clopidogrel 75mg', 'Tablet', '75mg', 'Sun Pharma'),
  ('Atorvastatin 10mg', 'Tablet', '10mg', 'Pfizer'),
  ('Atorvastatin 20mg', 'Tablet', '20mg', 'Pfizer'),
  ('Rosuvastatin 10mg', 'Tablet', '10mg', 'AstraZeneca'),
  ('Metformin 500mg', 'Tablet', '500mg', 'USV'),
  ('Metformin 1000mg', 'Tablet', '1000mg', 'USV'),
  ('Glimepiride 1mg', 'Tablet', '1mg', 'Sanofi'),
  ('Glimepiride 2mg', 'Tablet', '2mg', 'Sanofi'),
  ('Sitagliptin 100mg', 'Tablet', '100mg', 'MSD'),
  ('Voglibose 0.3mg', 'Tablet', '0.3mg', 'Torrent'),
  ('Insulin Glargine', 'Injection', '100IU/ml', 'Sanofi'),
  ('Vitamin D3 60000IU', 'Capsule', '60000IU', 'USV'),
  ('Vitamin B12 1500mcg', 'Tablet', '1500mcg', 'Abbott'),
  ('Calcium + Vitamin D3', 'Tablet', '500+250IU', 'Abbott'),
  ('Iron + Folic Acid', 'Tablet', '100+0.5mg', 'GSK'),
  ('Zinc 50mg', 'Tablet', '50mg', 'Mankind'),
  ('Multivitamin (Becosules)', 'Capsule', 'Multi', 'Pfizer'),
  ('Folic Acid 5mg', 'Tablet', '5mg', 'Alkem'),
  ('Omega-3 Fatty Acids', 'Capsule', '1000mg', 'Sun Pharma'),
  ('Prednisolone 10mg', 'Tablet', '10mg', 'Cadila'),
  ('Prednisolone 5mg', 'Tablet', '5mg', 'Cadila'),
  ('Methylprednisolone 8mg', 'Tablet', '8mg', 'Pfizer'),
  ('Dexamethasone 0.5mg', 'Tablet', '0.5mg', 'Cadila'),
  ('Hydrocortisone Cream', 'Cream', '1%', 'GSK'),
  ('Betamethasone Cream', 'Cream', '0.05%', 'GSK'),
  ('Diclofenac Gel', 'Gel', '1%', 'Novartis'),
  ('Mupirocin Ointment', 'Ointment', '2%', 'GSK'),
  ('Clotrimazole Cream', 'Cream', '1%', 'Bayer'),
  ('Silver Sulfadiazine Cream', 'Cream', '1%', 'Dr. Reddys'),
  ('Povidone Iodine Ointment', 'Ointment', '5%', 'Win Medicare'),
  ('Calamine Lotion', 'Cream', '8%', 'Lacto Calamine'),
  ('Ciprofloxacin Eye Drops', 'Drops', '0.3%', 'Cipla'),
  ('Tobramycin Eye Drops', 'Drops', '0.3%', 'Alcon'),
  ('Ofloxacin Eye Drops', 'Drops', '0.3%', 'Cipla'),
  ('Artificial Tears', 'Drops', '0.5%', 'Alcon'),
  ('Otosporin Ear Drops', 'Drops', 'Multi', 'GSK'),
  ('Fluconazole 150mg', 'Tablet', '150mg', 'Pfizer'),
  ('Itraconazole 100mg', 'Capsule', '100mg', 'Glenmark'),
  ('Terbinafine 250mg', 'Tablet', '250mg', 'Dr. Reddys'),
  ('Gelusil MPS', 'Syrup', '400mg/5ml', 'Pfizer'),
  ('Digene Gel', 'Syrup', '400mg/5ml', 'Abbott'),
  ('Lactulose Syrup', 'Syrup', '10g/15ml', 'Abbott'),
  ('Isabgol (Psyllium Husk)', 'Powder', '3.5g', 'Sat Isabgol'),
  ('Thiocolchicoside 4mg', 'Capsule', '4mg', 'Sanofi'),
  ('Chlorzoxazone 500mg', 'Tablet', '500mg', 'Intas'),
  ('Tizanidine 2mg', 'Tablet', '2mg', 'Sun Pharma'),
  ('Alprazolam 0.25mg', 'Tablet', '0.25mg', 'Torrent'),
  ('Escitalopram 10mg', 'Tablet', '10mg', 'Sun Pharma'),
  ('Amitriptyline 10mg', 'Tablet', '10mg', 'Intas'),
  ('Levothyroxine 50mcg', 'Tablet', '50mcg', 'Abbott'),
  ('Levothyroxine 100mcg', 'Tablet', '100mcg', 'Abbott');
  end if;
end $$;

do $$
begin
  if (select count(*) from lab_tests_catalog) = 0 then
    insert into lab_tests_catalog (name, category) values
  ('Complete Blood Count (CBC)', 'Blood'),
  ('Hemoglobin (Hb)', 'Blood'),
  ('Erythrocyte Sedimentation Rate (ESR)', 'Blood'),
  ('Peripheral Blood Smear', 'Blood'),
  ('Platelet Count', 'Blood'),
  ('Blood Group & Rh Typing', 'Blood'),
  ('Prothrombin Time (PT/INR)', 'Blood'),
  ('Reticulocyte Count', 'Blood'),
  ('Fasting Blood Sugar (FBS)', 'Diabetes'),
  ('Post Prandial Blood Sugar (PPBS)', 'Diabetes'),
  ('Random Blood Sugar (RBS)', 'Diabetes'),
  ('HbA1c (Glycated Hemoglobin)', 'Diabetes'),
  ('Oral Glucose Tolerance Test (OGTT)', 'Diabetes'),
  ('Fasting Insulin', 'Diabetes'),
  ('Liver Function Test (LFT)', 'Liver'),
  ('SGOT (AST)', 'Liver'),
  ('SGPT (ALT)', 'Liver'),
  ('Bilirubin (Total & Direct)', 'Liver'),
  ('Alkaline Phosphatase', 'Liver'),
  ('Gamma GT (GGT)', 'Liver'),
  ('Serum Albumin', 'Liver'),
  ('Hepatitis B Surface Antigen (HBsAg)', 'Liver'),
  ('Hepatitis C Antibody (Anti-HCV)', 'Liver'),
  ('Kidney Function Test (KFT)', 'Kidney'),
  ('Serum Creatinine', 'Kidney'),
  ('Blood Urea Nitrogen (BUN)', 'Kidney'),
  ('Serum Uric Acid', 'Kidney'),
  ('eGFR', 'Kidney'),
  ('Serum Electrolytes (Na/K/Cl)', 'Kidney'),
  ('Serum Calcium', 'Kidney'),
  ('Thyroid Profile (T3, T4, TSH)', 'Thyroid'),
  ('TSH (Thyroid Stimulating Hormone)', 'Thyroid'),
  ('Free T3', 'Thyroid'),
  ('Free T4', 'Thyroid'),
  ('Anti-TPO Antibodies', 'Thyroid'),
  ('Lipid Profile', 'Lipid'),
  ('Total Cholesterol', 'Lipid'),
  ('HDL Cholesterol', 'Lipid'),
  ('LDL Cholesterol', 'Lipid'),
  ('Triglycerides', 'Lipid'),
  ('VLDL Cholesterol', 'Lipid'),
  ('Urine Routine & Microscopy', 'Urine'),
  ('Urine Culture & Sensitivity', 'Urine'),
  ('24-Hour Urine Protein', 'Urine'),
  ('Urine Microalbumin', 'Urine'),
  ('Urine Pregnancy Test (UPT)', 'Urine'),
  ('ECG (Electrocardiogram)', 'Cardiac'),
  ('2D Echocardiography', 'Cardiac'),
  ('Troponin I', 'Cardiac'),
  ('CK-MB', 'Cardiac'),
  ('BNP / NT-proBNP', 'Cardiac'),
  ('Treadmill Test (TMT)', 'Cardiac'),
  ('C-Reactive Protein (CRP)', 'Infection'),
  ('Widal Test', 'Infection'),
  ('Dengue NS1 Antigen', 'Infection'),
  ('Dengue IgG/IgM', 'Infection'),
  ('Malaria Antigen (Rapid)', 'Infection'),
  ('Blood Culture & Sensitivity', 'Infection'),
  ('HIV 1 & 2 Antibody', 'Infection'),
  ('VDRL / RPR', 'Infection'),
  ('Mantoux Test (TB Skin Test)', 'Infection'),
  ('COVID-19 RT-PCR', 'Infection'),
  ('COVID-19 Rapid Antigen', 'Infection'),
  ('X-Ray Chest PA View', 'Imaging'),
  ('X-Ray (Specify Part)', 'Imaging'),
  ('Ultrasound Abdomen', 'Imaging'),
  ('Ultrasound Pelvis', 'Imaging'),
  ('CT Scan (Specify Region)', 'Imaging'),
  ('MRI (Specify Region)', 'Imaging'),
  ('Vitamin D (25-Hydroxy)', 'Other'),
  ('Vitamin B12', 'Other'),
  ('Serum Iron & TIBC', 'Other'),
  ('Serum Ferritin', 'Other'),
  ('RA Factor', 'Other'),
  ('ANA (Antinuclear Antibody)', 'Other'),
  ('PSA (Prostate Specific Antigen)', 'Other'),
  ('Semen Analysis', 'Other'),
  ('Stool Routine & Microscopy', 'Other'),
  ('Pap Smear', 'Other');
  end if;
end $$;
